plugins {
    id 'java'
    id("io.freefair.lombok") version "9.5.0"
    id("xyz.jpenilla.run-velocity") version "3.0.2"
}

group 'net.minecraftcapes'
version '1.2.0'

repositories {
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'com.velocitypowered:velocity-api:3.5.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.5.0-SNAPSHOT'

    compileOnly 'org.apache.logging.log4j:log4j-core:2.26.0'
}

tasks {
    runVelocity {
        velocityVersion('3.5.0-SNAPSHOT')
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    sourceCompatibility = targetCompatibility = 25
}